// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLAN_Switching.Data;

#nullable disable

namespace VLAN_Switching.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VLAN_Switching.Models.CampaignModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shopee",
                            VlanId = 76
                        });
                });

            modelBuilder.Entity("VLAN_Switching.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("tbl_Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Role = "Agent"
                        });
                });

            modelBuilder.Entity("VLAN_Switching.Models.StatusModel", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("tbl_Status");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            StatusId = 2,
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("VLAN_Switching.Models.SwitchPortModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwitchIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_SwitchPorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PortName = "Gi1/0/38",
                            SwitchIP = "10.5.2.34"
                        });
                });

            modelBuilder.Entity("VLAN_Switching.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("NTlogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("SwitchPortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("RoleID");

                    b.HasIndex("StatusId");

                    b.HasIndex("SwitchPortId");

                    b.ToTable("tbl_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampaignId = 1,
                            FullName = "Joe Quitalig",
                            IdNumber = 2025005704,
                            NTlogin = "Joe.Quitalig",
                            RoleID = 1,
                            StatusId = 1,
                            SwitchPortId = 1
                        });
                });

            modelBuilder.Entity("VLAN_Switching.Models.UserModel", b =>
                {
                    b.HasOne("VLAN_Switching.Models.CampaignModel", "Campaign")
                        .WithMany("tbl_Users")
                        .HasForeignKey("CampaignId");

                    b.HasOne("VLAN_Switching.Models.RoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.HasOne("VLAN_Switching.Models.StatusModel", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("VLAN_Switching.Models.SwitchPortModel", "SwitchPort")
                        .WithMany()
                        .HasForeignKey("SwitchPortId");

                    b.Navigation("Campaign");

                    b.Navigation("Role");

                    b.Navigation("Status");

                    b.Navigation("SwitchPort");
                });

            modelBuilder.Entity("VLAN_Switching.Models.CampaignModel", b =>
                {
                    b.Navigation("tbl_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
